### ISSUE TITLE
Formn accesses moment but it's not listed in its dependencies

### ISSUE THREAD

**Issue by joelwat** [benbotto/formn#6]
`Formn` makes `yarn 2` sad because moment isn't declared in its dependencies.

Error message from yarn:
```sh
(develop) [!?] is 📦 v0.0.1 via ⬢ v14.15.4 took 47s $ yarn run formn 
/home/joel/programming/covid-nestjs-api/.pnp.js:16966
    throw firstError;
    ^

Error: formn tried to access moment, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: moment (via "moment")
Required by: formn@npm:5.14.1 (via /home/joel/programming/covid-nestjs-api/.yarn/cache/formn-npm-5.14.1-6f3a1ed1f9-f536f7f0f8.zip/node_modules/formn/dist/migrator/)

Require stack:
- /home/joel/programming/covid-nestjs-api/.yarn/cache/formn-npm-5.14.1-6f3a1ed1f9-f536f7f0f8.zip/node_modules/formn/dist/migrator/migrator.js
- /home/joel/programming/covid-nestjs-api/.yarn/cache/formn-npm-5.14.1-6f3a1ed1f9-f536f7f0f8.zip/node_modules/formn/dist/migrator/index.js
- /home/joel/programming/covid-nestjs-api/.yarn/cache/formn-npm-5.14.1-6f3a1ed1f9-f536f7f0f8.zip/node_modules/formn/dist/index.js
- /home/joel/programming/covid-nestjs-api/.yarn/cache/formn-cli-npm-1.2.1-6cacbf11b7-afb4784ed3.zip/node_modules/formn-cli/dist/lib/cli-model-generator.js
- /home/joel/programming/covid-nestjs-api/.yarn/cache/formn-cli-npm-1.2.1-6cacbf11b7-afb4784ed3.zip/node_modules/formn-cli/dist/lib/index.js
- /home/joel/programming/covid-nestjs-api/.yarn/cache/formn-cli-npm-1.2.1-6cacbf11b7-afb4784ed3.zip/node_modules/formn-cli/dist/bin/formn.js
    at internalTools_makeError (/home/joel/programming/covid-nestjs-api/.pnp.js:16710:34)
    at resolveToUnqualified (/home/joel/programming/covid-nestjs-api/.pnp.js:17675:23)
    at resolveRequest (/home/joel/programming/covid-nestjs-api/.pnp.js:17767:29)
    at Object.resolveRequest (/home/joel/programming/covid-nestjs-api/.pnp.js:17845:26)
    at Function.external_module_.Module._resolveFilename (/home/joel/programming/covid-nestjs-api/.pnp.js:16943:34)
    at Function.external_module_.Module._load (/home/joel/programming/covid-nestjs-api/.pnp.js:16808:48)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/joel/programming/covid-nestjs-api/.yarn/cache/formn-npm-5.14.1-6f3a1ed1f9-f536f7f0f8.zip/node_modules/formn/dist/migrator/migrator.js:12:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
```

**Comment by joelwat** [comment]
PR: https://github.com/benbotto/formn/pull/7

**Comment by benbotto** [comment]
Thanks for the PR.  I merged it in and bumped a few dev dependencies that had vulnerabilities, all of which were sub-dependencies of typedoc.  New release is 5.14.2.
